---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cni-plugins
rules:
  - apiGroups: ["k8s.cni.cncf.io"]
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/status
    verbs:
      - get
      - update
  - apiGroups:
      - ""
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
      - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cni-plugins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cni-plugins
subjects:
  - kind: ServiceAccount
    name: cni-plugins
    namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cni-plugins
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-cni-plugins-ds
  namespace: kube-system
  labels:
    tier: node
    app: cni-plugins
    name: cni-plugins
spec:
  selector:
    matchLabels:
      name: cni-plugins
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: cni-plugins
        name: cni-plugins
    spec:
      hostNetwork: true
      # hostPID required for dhcp to see all netns
      hostPID: true
      tolerations:
        - operator: Exists
          effect: NoSchedule
        - operator: Exists
          effect: NoExecute
      serviceAccountName: cni-plugins
      containers:
        - name: dhcp-daemon
          image: ghcr.io/deekue/docker-cni-plugins:v1.1.1-0.1
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "100m"
              memory: "50Mi"
          securityContext:
            privileged: true
          volumeMounts:
            - name: cni
              mountPath: /host/etc/cni/net.d
            - name: cnibin
              mountPath: /host/opt/cni/bin
            - name: run
              mountPath: /run
      initContainers:
        - name: install-cni-plugins
          image: ghcr.io/deekue/docker-cni-plugins:v1.1.1-0.1
          command:
            - "/bin/sh"
            - "-c"
            - "cp -v /plugins/* /host/opt/cni/bin/"
          resources:
            requests:
              cpu: "10m"
              memory: "15Mi"
          securityContext:
            privileged: true
          volumeMounts:
            - name: cnibin
              mountPath: /host/opt/cni/bin
              mountPropagation: Bidirectional
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cni
          hostPath:
            path: /etc/cni/net.d
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
        - name: run
          hostPath:
            path: /run
